/**Tecnologias
ODAC 12.2c Release 1 and Oracle Developer Tools for Visual Studio (12.2.0.1.1)
Visual Studio Communty 2019 Preview
Oracle SQL Developer 19.2.1.247.2212-x64
Oracle OraDB18Home1
ASP.NET Webforms 4.7
Oracle.ManagedDataAccess 19.7.0
**/
CREATE TABLE Mesa(
    NroMesa NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR2(100) NOT NULL,
    Reservada BOOLEAN NULL,
    PRIMARY KEY(NroMesa)
);
CREATE TABLE Supervisor(
    IdSupervisor NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Nombres VARCHAR2(100) NOT NULL,
	Apellidos VARCHAR2(100) NOT NULL,
	Antiguedad NUMBER NULL,
    PRIMARY KEY(NroMesa)
);
CREATE TABLE Mesero(
    IdMesero NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Nombres VARCHAR2(100) NOT NULL,
	Apellidos VARCHAR2(100) NOT NULL,
	Edad NUMBER NULL,
	Antiguedad NUMBER not NULL,
    PRIMARY KEY(NroMesa)
);
CREATE TABLE Cliente(
    Identificacion NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Nombres VARCHAR2(100) NOT NULL,
	Apellidos VARCHAR2(100) NOT NULL,
	Direccion VARCHAR2 (100) null,
	Telefono VARCHAR2(50) null,
    PRIMARY KEY(Identificacion)
);

CREATE TABLE Plato
( IdPlato NUMBER GENERATED BY DEFAULT AS IDENTITY,
  Nombre varchar2(100) not null,
  Valor number not null,
  CONSTRAINT  plato_pk
    primary KEY (IdPlato)
);

CREATE TABLE DetallexFactura
( IdDetallexFactura NUMBER GENERATED BY DEFAULT AS IDENTITY,
  NroFactura number not null,
  IdSupervisor number not null,
  Plato number not null,
  Valor number not null,
    PRIMARY KEY(IdDetallexFactura)
);
ALTER TABLE DetallexFactura
ADD CONSTRAINT supervisor_fk
  FOREIGN KEY (IdSupervisor)
  REFERENCES Supervisor(IdSupervisor);

ALTER TABLE DetallexFactura
ADD CONSTRAINT Plato_fk
  FOREIGN KEY (Plato)
  REFERENCES Plato(IdPlato);

CREATE TABLE Factura
( NroFactura NUMBER GENERATED BY DEFAULT AS IDENTITY,
   IdCliente number not null,
  NroMesa number not null,
  IdMesero number not null,
  Fecha	 date not null,
    CONSTRAINT  Factura_pk
    PRIMARY KEY(NroFactura)
);

ALTER TABLE DetallexFactura
ADD CONSTRAINT Factura_fk
  FOREIGN KEY (NroFactura)
  REFERENCES Factura(NroFactura);

ALTER TABLE Factura
ADD CONSTRAINT IdCliente_fk
  FOREIGN KEY (IdCliente)
  REFERENCES Cliente(Identificacion);
  
  ALTER TABLE Factura
ADD CONSTRAINT Mesa_fk
  FOREIGN KEY (NroMesa)
  REFERENCES Mesa(NroMesa);
  
    ALTER TABLE Factura
ADD CONSTRAINT IdMesero_fk
  FOREIGN KEY (IdMesero)
  REFERENCES IMesero(IdMesero);
  
  insert into cliente (identificacion,nombres,apellidos) values(1234,'Diego','Programador')
    insert into cliente (identificacion,nombres,apellidos) values(1234,'juana','Diseñadora')
	insert into cliente (identificacion,nombres,apellidos) values(1234,'Mariana','Administradora')

