//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEXFACTURA
    {
        public decimal IDDETALLEXFACTURA { get; set; }
        public decimal NROFACTURA { get; set; }
        public decimal IDSUPERVISOR { get; set; }
        public decimal PLATO { get; set; }
        public decimal VALOR { get; set; }
    
        public virtual FACTURA FACTURA { get; set; }
        public virtual PLATO PLATO1 { get; set; }
        public virtual SUPERVISOR SUPERVISOR { get; set; }
    }
}
