//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public FACTURA()
        {
            this.DETALLEXFACTURA = new HashSet<DETALLEXFACTURA>();
        }
    
        public decimal NROFACTURA { get; set; }
        public decimal IDCLIENTE { get; set; }
        public decimal NROMESA { get; set; }
        public decimal IDMESERO { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<DETALLEXFACTURA> DETALLEXFACTURA { get; set; }
        public virtual MESERO MESERO { get; set; }
        public virtual MESA MESA { get; set; }
    }
}
