//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESA
    {
        public MESA()
        {
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public decimal NROMESA { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<short> RESERVADA { get; set; }
    
        public virtual ICollection<FACTURA> FACTURA { get; set; }
    }
}
