//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESERO
    {
        public MESERO()
        {
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public decimal IDMESERO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public Nullable<decimal> EDAD { get; set; }
        public decimal ANTIGUEDAD { get; set; }
    
        public virtual ICollection<FACTURA> FACTURA { get; set; }
    }
}
