//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<DETALLEXFACTURA> DETALLEXFACTURA { get; set; }
        public DbSet<FACTURA> FACTURA { get; set; }
        public DbSet<MESA> MESA { get; set; }
        public DbSet<MESERO> MESERO { get; set; }
        public DbSet<PLATO> PLATO { get; set; }
        public DbSet<SUPERVISOR> SUPERVISOR { get; set; }
    }
}
