//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPERVISOR
    {
        public SUPERVISOR()
        {
            this.DETALLEXFACTURA = new HashSet<DETALLEXFACTURA>();
        }
    
        public decimal IDSUPERVISOR { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public Nullable<decimal> ANTIGUEDAD { get; set; }
    
        public virtual ICollection<DETALLEXFACTURA> DETALLEXFACTURA { get; set; }
    }
}
